### ISSUE TITLE
Will this be published to NPM

### ISSUE THREAD

**Issue by lritter79** [danielpetho/fancy#1]
Hey, I checked out your docs and I like this project. I see that you currently just support copy/pasting versus install the components to a project as an NPM. Will you publish this repo with the components to use as an NPM package, or continue using your current model? I don't think there's a right or wrong way, I'm just curious

**Comment by danielpetho** [comment]
hey! thanks for checking out the project and for your question!
In short, I don’t plan to distribute it as an NPM package.

The idea is inspired by how the [shadcn](https://ui.shadcn.com/docs) library is set up. The main reason is that most components in the catalog are unfortunately narrow in scope and may fall short for specific use cases. (eg, for a site I wanted combine two really similar components — [scramble-in](https://www.fancycomponents.dev/docs/components/text/scramble-in) and [scramble-hover](https://www.fancycomponents.dev/docs/components/text/scramble-hover) — but without some custom hacking, it's not possible right now)

I will try to make the components customizable as much as possible via external styling and logic, you’ll likely need to modify the source code for specific use-cases. With the copy-paste model, I feel like it's much easier to access and customize the implementation—and you’ll only take what you need.
